export default {
  DATE_FORMAT: "DD.MM.YYYY",
  DB_DATE_FORMAT: "YYYY-MM-DD",
  DATE_TIME_FORMAT: "DD.MM.YY (LT)",
  LICENCE_STATUS_NOT_STARTED: 0,
  LICENCE_STATUS_NEW: 1,

  LICENCE_STATUS_ON_REVIEW: 10,  // na rsmotr
  LICENCE_STATUS_ACTIVE: 20, // deistv
  LICENCE_STATUS_INACTIVE: 30,  // deaktivirovan
};
